version: '2'
services:
   db:
     build:
       context: ../../
       dockerfile: ./docker/development/Dockerfile_postgres
     ports:
       - "5432:5432"
     command: bash -c "/usr/lib/postgresql/9.6/bin/postgres -D /var/lib/postgresql/9.6/main -c config_file=/etc/postgresql/9.6/main/postgresql.conf"

   example:
     build:
       context: ../../
       dockerfile: ./docker/development/Dockerfile
     command: bash -c "/usr/bin/wait-for-it.sh db python3 /{{project_name}}/src/manage.py runserver --settings config.docker_development"
     ports:
       - "9011:9011"
     depends_on:
       - db
     links:
       - db:db
